# Generated by Django 4.1.2 on 2022-11-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(blank=True, choices=[('Poodle', 'Poodle'), ('German Shepherd', 'German Shepherd'), ('Chihuahua', 'Chihuahua'), ('Mut', 'Mut'), ('Labrador', 'Labrador'), ('DSH', 'Domestic Short Hair'), ('DLH', 'Domestic Long Hair'), ('Siamese', 'Siamese'), ('Russian Blue', 'Russian Blue'), ('Maine Coon', 'Maine Coon'), ('Fish', 'Fish'), ('Snake', 'Snake'), ('Turtle', 'Turtle'), ('Iguana', 'Iguana')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition_1', models.CharField(blank=True, choices=[('Good with children', 'Good with children'), ('Good with other animals', 'Good with other animals'), ('Must be leashed at all times', 'Must be leashed at all times')], max_length=50)),
                ('disposition_2', models.CharField(blank=True, choices=[('Good with children', 'Good with children'), ('Good with other animals', 'Good with other animals'), ('Must be leashed at all times', 'Must be leashed at all times')], max_length=50)),
                ('disposition_3', models.CharField(blank=True, choices=[('Good with children', 'Good with children'), ('Good with other animals', 'Good with other animals'), ('Must be leashed at all times', 'Must be leashed at all times')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Reptile', 'Reptile'), ('Other', 'Other')], default='Dog', max_length=10)),
                ('age', models.CharField(choices=[('Baby', 'Baby'), ('Young', 'Young'), ('Adult', 'Adult'), ('Senior', 'Senior')], default='Baby', max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default='Male', max_length=10)),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available'), ('Pending', 'Pending'), ('Adopted', 'Adopted')], default='Available', max_length=15)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
