# Generated by Django 4.1.2 on 2022-11-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='headshots/default.jpeg', upload_to='headshots')),
                ('name', models.CharField(max_length=25)),
                ('type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Reptile', 'Reptile'), ('Other', 'Other')], default='Dog', max_length=10)),
                ('breed', models.CharField(blank=True, choices=[('Poodle', 'Poodle'), ('German Shepherd', 'German Shepherd'), ('Chihuahua', 'Chihuahua'), ('Mut', 'Mut'), ('Labrador', 'Labrador'), ('Domestic Short Hair', 'Domestic Short Hair'), ('Domestic Long Hair', 'Domestic Long Hair'), ('Siamese', 'Siamese'), ('Russian Blue', 'Russian Blue'), ('Main Coon', 'Main Coon'), ('Fish', 'Fish'), ('Snake', 'Snake'), ('Turtle', 'Turtle'), ('Iguana', 'Iguana')], max_length=50)),
                ('age', models.CharField(choices=[('Baby', 'Baby'), ('Young', 'Young'), ('Adult', 'Adult'), ('Senior', 'Senior')], default='Baby', max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('good_with_children', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('good_with_other_animals', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('must_be_leashed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available'), ('Pending', 'Pending'), ('Adopted', 'Adopted')], default='Available', max_length=15)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('news_blurb', models.CharField(blank=True, default='', max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
