# Generated by Django 4.1.2 on 2022-11-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ages',
            name='age',
            field=models.CharField(choices=[('Baby', 'Baby'), ('Young', 'Young'), ('Adult', 'Adult'), ('Senior', 'Senior')], max_length=25),
        ),
        migrations.AlterField(
            model_name='types',
            name='type',
            field=models.CharField(choices=[('D', 'Dog'), ('C', 'Cat'), ('R', 'Reptile'), ('O', 'Other')], max_length=25),
        ),
    ]
