# Generated by Django 4.1.2 on 2022-11-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ages_age_alter_types_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Codes',
        ),
        migrations.RenameField(
            model_name='pets',
            old_name='disposition_description',
            new_name='disposition',
        ),
        migrations.RemoveField(
            model_name='dispositions',
            name='disposition_description',
        ),
        migrations.AddField(
            model_name='dispositions',
            name='disposition_1',
            field=models.CharField(blank=True, choices=[('Good with children', 'Good with children'), ('Good with other animals', 'Good with other animals'), ('Must be leashed at all times', 'Must be leashed at all times')], max_length=50),
        ),
        migrations.AddField(
            model_name='dispositions',
            name='disposition_2',
            field=models.CharField(blank=True, choices=[('Good with children', 'Good with children'), ('Good with other animals', 'Good with other animals'), ('Must be leashed at all times', 'Must be leashed at all times')], max_length=50),
        ),
        migrations.AddField(
            model_name='dispositions',
            name='disposition_3',
            field=models.CharField(blank=True, choices=[('Good with children', 'Good with children'), ('Good with other animals', 'Good with other animals'), ('Must be leashed at all times', 'Must be leashed at all times')], max_length=50),
        ),
        migrations.AlterField(
            model_name='breeds',
            name='breed',
            field=models.CharField(blank=True, choices=[('Poodle', 'Poodle'), ('German Shepherd', 'German Shepherd'), ('Chihuahua', 'Chihuahua'), ('Mut', 'Mut'), ('Labrador', 'Labrador'), ('DSH', 'Domestic Short Hair'), ('DLH', 'Domestic Long Hair'), ('Siamese', 'Siamese'), ('Russian Blue', 'Russian Blue'), ('Maine Coon', 'Maine Coon'), ('Fish', 'Fish'), ('Snake', 'Snake'), ('Turtle', 'Turtle'), ('Iguana', 'Iguana')], max_length=50),
        ),
    ]
