# Generated by Django 4.1.2 on 2022-11-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_breeds_delete_dispositions_pet_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='news_blurb',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
