# Generated by Django 4.1.2 on 2022-11-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20221123_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.FileField(default='headshots/default.jpeg', upload_to='headshots/'),
        ),
    ]
