export const sampleData = [
  {
    id: 1,
    type: 'Dog',
    age: 'Baby',
    availability: 'Available',
    disposition: ['Good with other animals', 'Good with children', 'Animal must be leashed at all times'],
    description: 'blahblahblah',
    last_updated: 'etc',
    date_created: 'etc',
    name: 'Joe1',
    breed: 'doga'
  },
  {
    id: 2,
    type: 'Dog',
    age: 'Baby',
    availability: 'Available',
    disposition: ['Good with other animals', 'Good with children'],
    description: 'blahblahblah',
    last_updated: 'etc',
    date_created: 'etc',
    name: 'Joe2',
    breed: 'doga'
  },
  {
    id: 3,
    type: 'Dog',
    age: 'Baby',
    availability: 'Available',
    disposition: ['Good with children', 'Animal must be leashed at all times'],
    description: 'blahblahblah',
    last_updated: 'etc',
    date_created: 'etc',
    name: 'Joe3',
    breed: 'doga'
  },
  {
    id: 4,
    type: 'Dog',
    age: 'Baby',
    availability: 'Available',
    disposition: ['Good with other animals', 'Animal must be leashed at all times'],
    description: 'blahblahblah',
    last_updated: 'etc',
    date_created: 'etc',
    name: 'Joe4',
    breed: 'doga'
  },
  {
    id: 5,
    type: 'Dog',
    age: 'Baby',
    availability: 'Available',
    disposition: ['Good with other animals'],
    description: 'blahblahblah',
    last_updated: 'etc',
    date_created: 'etc',
    name: 'Joe5',
    breed: 'doga'
  },
  {
    id: 6,
    type: 'Dog',
    age: 'Baby',
    availability: 'Available',
    disposition: ['Good with children'],
    description: 'blahblahblah',
    last_updated: 'etc',
    date_created: 'etc',
    name: 'Joe6',
    breed: 'doga'
  },
  {
    id: 7,
    type: 'Dog',
    age: 'Baby',
    availability: 'Available',
    disposition: ['Animal must be leashed at all times'],
    description: 'blahblahblah',
    last_updated: 'etc',
    date_created: 'etc',
    name: 'Joe7',
    breed: 'doga'
  },
  {
    id: 8,
    type: 'Dog',
    age: 'Baby',
    availability: 'Pending',
    disposition: [],
    description: 'blahblahblah',
    last_updated: 'etc',
    date_created: 'etc',
    name: 'Joe8',
    breed: 'doga'
  },
  {
    id: 9,
    type: 'Dog',
    age: 'Senior',
    availability: 'Unavailable',
    disposition: [],
    description: 'blahblahblah',
    last_updated: 'etc',
    date_created: 'etc',
    name: 'Joe9',
    breed: 'doga'
  },
  {
    id: 10,
    type: 'Cat',
    age: 'Baby',
    availability: 'Available',
    disposition: ['Good with other animals', 'Good with children', 'Animal must be leashed at all times'],
    description: 'blahblahblah',
    last_updated: 'etc',
    date_created: 'etc',
    name: 'Ann1',
    breed: 'cata'
  },
  {
    id: 11,
    type: 'Cat',
    age: 'Baby',
    availability: 'Available',
    disposition: ['Good with other animals', 'Good with children'],
    description: 'blahblahblah',
    last_updated: 'etc',
    date_created: 'etc',
    name: 'Ann2',
    breed: 'cata'
  },
  {
    id: 12,
    type: 'Cat',
    age: 'Baby',
    availability: 'Available',
    disposition: ['Good with children', 'Animal must be leashed at all times'],
    description: 'blahblahblah',
    last_updated: 'etc',
    date_created: 'etc',
    name: 'Ann3',
    breed: 'cata'
  },
  {
    id: 13,
    type: 'Cat',
    age: 'Baby',
    availability: 'Available',
    disposition: ['Good with other animals', 'Animal must be leashed at all times'],
    description: 'blahblahblah',
    last_updated: 'etc',
    date_created: 'etc',
    name: 'Ann4',
    breed: 'cata'
  },
  {
    id: 14,
    type: 'Cat',
    age: 'Baby',
    availability: 'Available',
    disposition: ['Good with other animals'],
    description: 'blahblahblah',
    last_updated: 'etc',
    date_created: 'etc',
    name: 'Ann5',
    breed: 'cata'
  },
  {
    id: 15,
    type: 'Cat',
    age: 'Baby',
    availability: 'Available',
    disposition: ['Good with children'],
    description: 'blahblahblah',
    last_updated: 'etc',
    date_created: 'etc',
    name: 'Ann6',
    breed: 'cata'
  },
  {
    id: 16,
    type: 'Cat',
    age: 'Baby',
    availability: 'Available',
    disposition: ['Animal must be leashed at all times'],
    description: 'blahblahblah',
    last_updated: 'etc',
    date_created: 'etc',
    name: 'Ann7',
    breed: 'cata'
  },
  {
    id: 17,
    type: 'Cat',
    age: 'Baby',
    availability: 'Pending',
    disposition: [],
    description: 'blahblahblah',
    last_updated: 'etc',
    date_created: 'etc',
    name: 'Ann8',
    breed: 'cata'
  },
  {
    id: 18,
    type: 'Cat',
    age: 'Senior',
    availability: 'Unavailable',
    disposition: [],
    description: 'blahblahblah',
    last_updated: 'etc',
    date_created: 'etc',
    name: 'Ann9',
    breed: 'cata'
  },
]